### ISSUE TITLE
macOS Big Sur 11.6 (20G165) checksum

### ISSUE THREAD

**Issue by syouko** [notpeter/apple-installer-checksums#137] opened 2021-09-26 16:17 UTC
~ % shasum /Applications/Install\ macOS\ Big\ Sur.app/Contents/SharedSupport/SharedSupport.dmg

**2e89d67ebb02d1c655dfb875144e2c15bd6fa726**  /Applications/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg

~ % sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

That's my result
Hope can provide some help :P

**Comment by sapperlott** [comment] 2021-09-27 05:11
I can confirm that SHA1 hash - same here.

**Comment by markmentovai** [comment] 2021-09-27 14:13
Thanks! We already have #135 for this, but we can treat this as confirmation.

Duplicate of #135

**Comment by markmentovai** [comment] 2021-09-27 14:13
Duplciate of #135

**Comment by markmentovai** [comment] 2021-09-27 14:13
Duplicate of #135

**Closed** 2022-02-11 20:06 UTC
