### ISSUE TITLE
Why do we care about the dmgs only?

### ISSUE THREAD

**Issue by crazy2k** [notpeter/apple-installer-checksums#29] opened 2017-10-16 08:56 UTC
Hi! The .app installation bundle has many files other than the dmgs. Why don't we care about them being legit too? Am I missing something?

Thank you.

**Comment by ciaranconnor** [comment] 2017-10-17 01:54
I'm not sure 100% sure, but here's my speculation for the reasoning behind only caring about the `.dmg` files (assuming you are asking about the OS X installers; for Xcode it's easier to just grab the versioned releases from https://developer.apple.com/download/more/, rather than trying to archive or verify the App Store version):

1. `InstallESD.dmg` is a single file and is read-only when attached, so calculating and verifying its checksum is always simple, clean, and consistent. The same can't be said for the `.app`, which is a folder structure, and includes `Contents/_MASReceipt/receipt`—which, if memory serves me right, is unique to the Apple ID used to download the installer from the App Store.

2. There is actually a version of the `.app` inside `InstallESD.dmg`—well at least there is for the Sierra installer I've got in front of me. For example, if I `hdiutil attach /Applications/Install\ macOS\ Sierra.app/Contents/SharedSupport/InstallESD.dmg` followed by `hdiutil attach /Volumes/OS\ X\ Install\ ESD/BaseSystem.dmg`, then I get `Install macOS Sierra.app` under `/Volumes/OS X Base System`. It appears to be the same as the App Store version, minus the `Contents/_MASReceipt/receipt`.

Let me know if I'm wrong. I've just been yanking and archiving the `InstallESD.dmg` files, then discarding the App Store `.app`, as I've been assuming they become redundant.

**Comment by markmentovai** [comment] 2017-10-17 14:51
`InstallESD.dmg` usually used to contain everything needed for a complete installation. For most (but not all) 10.12-series releases, if you interpreted `InstallESD.dmg` as a `.pkg`, you’d find `InstallOS.pkg` hiding inside, which contained the installer `.app`. If you received an untrustworthy `.app`, it was possible to verify the hash of `InstallESD.dmg` and just use that, and throw the rest of the `.app` away. As of 10.13, this is no longer true.

The installer `.app` in `BaseSystem.dmg` was subtly different than the one you’d see installed by the App Store into /Applications, but the one in `InstallOS.pkg` inside `InstallESD.dmg` was the same.

In 10.13, there’s still an `InstallOS.pkg` inside `InstallESD.dmg`, but it doesn’t contain the installer `.app`. `BaseSystem.dmg` still has a subtly different copy of the installer, but `BaseSystem.dmg` is no longer part of `InstallESD.dmg`. So as of 10.13, I think that more than `InstallESD.dmg` is needed. That’s why I’ve been saving `BaseSystem.dmg` hashes too.

(In 10.13, the _MASReceipt is gone, too.)

It’s possible that we should be hashing and saving more than we are.

**Comment by 3ji7ja0jb9c** [comment] 2017-12-18 04:55
I do not care much about the dmgs.  [I care about volume/slice/partition/filesystem _content_.](/drduh/macOS-Security-and-Privacy-Guide/issues/125#issuecomment-235416026)

[Macintosh Garden is preserving checksums of BaseSystem.dmg since 2015.](http://macintoshgarden.org/apps/mac-os-x-intel-microprocessor)

**Comment by notpeter** [comment] 2018-06-11 17:20
@3ji7ja0jb9c While that's interesting, I have no interest in tracking hashes of the restored content since that is inherently not platform portable and requires restoring potentially malicious content in before validating it's authenticity.  The primary purpose of this repo is to prevent people who need to test multiple OSX / XCode versions validating that their installers have not been corrupted/infected due to bitrot or malicious action.

The reasoning behind tracking just DMGs is that a DMG alone was sufficient to reinstall a clean system when I created this project.  That has become less true over time (now `InstallESD.dmg`, `BaseSystem.dmg` and [`createinstallmedia`](https://support.apple.com/en-us/ht201372) among others) are actually required.  My assumption beginning with 10.8 was that the Apple provided `_CodeSignature` is sufficient for most people running the app bundle to verify its authenticity, but that those installing on a fresh system or in a Virtual Machine (from dmg) were offered no such assurances. 

The real practical concern is how to validate checksum for many individual files (latest Install High Sierra app bundle has 627 files in 310 directories). Every scenario I've imagined to track this adds significant complexity (custom scripts/software to generate & validate checksums, etc) and makes checksums less likely to actually be verified. That said, I'm happy to consider actionable proposals to track the complete bundle.

**Comment by osuskates** [comment] 2018-08-10 13:00
I'd like to recommend using md5deep/hashdeep against the MacOS installer .app file and then posting the resulting output file (which contains hashes for all of the files all the way down the directory tree) for others to download and use. Those wanting to verify their installer media/files can use the same program and set a few different options/flag to get desired results.

Steps:

For new MacOS releases, do the following to create a master/verify list for the community:
1) Install both md5deep/hashdeep with something like "brew install md5deep"
2) hashdeep -c sha256 -e -r "/Applications/Install macOS High Sierra.app" > ~/Desktop/hashdeep_listing_sha256_MacOS_Installer_High_Sierra_10.13.6.txt
3) Take a peek at the text file to insure everything looks good: less ~/Desktop/hashdeep_listing_sha256_MacOS_Installer_High_Sierra_10.13.6.txt
4) Grab a SHA-256 hash of the listing (yes, one could argue this step could be optional as this does a a good job at making sure you didn't have any random errors in your download and that no changes were made, but it doesn't help you figure out whether you downloaded a file created by a bad guy - who happened to post a malicious listing to the website or MitM your connection - and not the developer): shasum -a 256 ~/Desktop/hashdeep_listing_sha256_MacOS_Installer_High_Sierra_10.13.6.txt
5) Sign the hashdeep_listing file with GnuPG which will result in a .asc file and tell us how to get your public key.
6) Post the text file (hashdeep_listing_sha256_MacOS_Installer_High_Sierra_10.13.6.txt), SHA-256 hash of the file (performed in step #4), and hashdeep_listing_sha256_MacOS_Installer_High_Sierra_10.13.6.txt.asc (performed in step #5) files to this GitHub repository.

For users who want to verify their media:
1) Install both md5deep/hashdeep with something like "brew install md5deep"
2) Download the hashdeep_listing_sha256_MacOS_Installer_<version>.txt and hashdeep_listing_sha256_MacOS_Installer_<version>.txt.asc files from this site.
3) Grab a SHA-256 hash of file (this is a good integrity check, but not that you received the file the developer intended you to have that he signed with his private GnuPG key): shasum -a 256 ~/Desktop/hashdeep_listing_sha256_MacOS_Installer_<version>.txt and compare with the one posted on the website. If not the same, corrupt, tampered with or partial file? Re-download?
4) Check the signature of the hashdeep_listing_sha256_MacOS_Installer_<version>.txt file after importing the developers public GnuPG key: gpg --verify hashdeep_listing_sha256_MacOS_Installer_<version>.txt.asc (both files need to be in the same directory)
5) Assuming everything checks out and you have a good file that hasn't been tampered with you can use something like this to see if all of the files match and which ones do not:
hashdeep -c sha256 -e -a -v -v -v -k ~/Desktop/hashdeep_listing_sha256_MacOS_Installer_<version>.txt -r "Install macOS High Sierra.app"/ | grep "No match"

All of the files save for the Contents/_MASReceipt/receipt file mentioned above should be the same. If not, investigate.

References: http://md5deep.sourceforge.net

Thoughts/Modifications?

**Comment by leszek-s** [comment] 2019-02-12 20:40
Based on https://stackoverflow.com/questions/545387/linux-compute-a-single-hash-for-a-given-folder-contents this command should work properly:

find Install\ macOS\ Mojave.app/ -type f -print0 | sort -z | xargs -0 shasum | shasum

Note that it should be executed from the folder which contains "Install macOS Mojave.app" because we need to give a relative path to find command. For macOS 10.14.2 (with da00f1ccb5e0927ae4550fd8399160cc5f3a9b47 InstallESD.dmg and 90c513f9a497fc3684f1d33f8c44a13c2dd35aa5 BaseSystem.dmg) above command to calculate a single hash for this directory gives me this result:
45adc7c5751844a2fef5f320f6cca1dfe16aa026

If someone else can check if he also gets the same result for this macOS 10.14.2 then we can confirm if it works as expected.

**Comment by bracklanna** [comment] 2019-02-24 22:45
I don't have an 10.14.2 installer. Can anyone verify the following results for 10.14.3? (Downloaded today from the Apple App Store):

find /Applications/Install\ macOS\ Mojave.app/ -type f -print0 | sort -z | xargs -0 shasum | shasum

For macOS 10.14.3:
InstallESD.dmg:  51493681f3e82bb78e22e97f38725ffc67f611cd 
BaseSystem.dmg: 39059732811393335b3ebeac1391aeed905e76de

Using the above command to calculate a single hash for this directory gives me this result:
c7e7fa5c4d8812bd33c407e1cdae0e7c8dfdb0bc

Can we get a few more verifications of these, & then have them updated on the main page list of checksums?

**Comment by markmentovai** [comment] 2019-02-25 22:22
I don’t believe that `find`-`shasum`-pipe-to-`shasum` is truly viable. It may be fine for quick and dirty local comparisons, but it’s inadequate for large-scale hash publication.

**It’s sensitive to way that find was invoked, including the pathname that was used.** The `find`-based suggestions above both have trailing slashes (Install macOS Mojave.app/) which become part of the outer hash, which won’t agree with the same “find” run without the trailing slash. The suggestions above both vary in the path supplied (/Applications vs. not) which will also become part of the outer hash. There’s no reason to advertise hashes so dependent on the path. There’s no reason `(cd /Applications; hash_it_all.sh 'Install macOS Mojave.app')` should vary at all from `hash_it_all.sh '/Applications/Install macOS Mojave.app'`. And there’s no reason that someone who’s archived this installer under a different name (say, 'Install macOS Mojave 10.14.3 18D42.app') shouldn’t be able to validate their copy despite having renamed it, without having to jump through hoops.

**It ignores symbolic links and directories.** Both of the `find`-based suggestions above use `-type f` which restrict hashing to regular files only. There may be inner symbolic links or empty directories that are meaningful, or the introduction of new inner symbolic links or directories could be meaningful. A proper hash should not ignore this.

**It’s insensitive to filesystem metadata.** Sometimes, timestamps are significant. Sometimes, they’re not. These installer .apps are tricky because the timestamps are supposed to be well-defined for some set of inner files, but not others (notably, the big inner .dmgs). But even assuming that people are generally comfortable with timestamps not being covered, there are substantive alterations to inner file metadata that the hash ought to capture. For example, a change as simple as setting or clearing the executable bit on inner files could alter the installer’s behavior or break it entirely, and these sorts of modifications should be covered by the hash.

**Sorting is nontrivial.** The `find`-based suggestions above use `sort`. Unaided, this sorts according to the system’s locale. Because the sort order becomes part of the outer hash, sorting needs to be done in a deterministic way.

**It’s sensitive to shasum’s output format.** Lowercase hexadecimal hash, two spaces, path, newline. None of these are actually nailed down very well. Is the hash always lowercase hexadecimal? Are there always two spaces? What’s the encoding of the pathname? What character or sequence is being used for newlines? What if some BSD user wants to use sha1 instead of shasum? This is unnecessarily dependent on the precise output of a specific program.

It’s possible to overcome some of these through the application of duct tape, but it’d be better if it were done properly, without the sorts of quirky dependencies that result from stringing a bunch of command-line tools together in a pipeline.

**Comment by bracklanna** [comment] 2019-02-25 22:25
Excellent analysis, I agree completely with all points.

Can anyone confirm these plain (single-file) hashes for 10.4.3 as downloaded from the Apple Store, yesterday? (I assume still current.)

InstallESD.dmg: 51493681f3e82bb78e22e97f38725ffc67f611cd
BaseSystem.dmg: 39059732811393335b3ebeac1391aeed905e76de

**Comment by osuskates** [comment] 2019-02-25 22:33
> Excellent analysis, I agree completely with all points.
> 
> Can anyone confirm these plain (single-file) hashes for 10.4.3 as downloaded from the Apple Store, yesterday? (I assume still current.)
> 
> InstallESD.dmg: 51493681f3e82bb78e22e97f38725ffc67f611cd
> BaseSystem.dmg: 39059732811393335b3ebeac1391aeed905e76de

While I don't believe these are from Apple, Inc. itself, SHA1 Hashes can be found here: https://github.com/notpeter/apple-installer-checksums

**Comment by bracklanna** [comment] 2019-02-25 22:35
> > Excellent analysis, I agree completely with all points.
> > Can anyone confirm these plain (single-file) hashes for 10.4.3 as downloaded from the Apple Store, yesterday? (I assume still current.)
> > InstallESD.dmg: 51493681f3e82bb78e22e97f38725ffc67f611cd
> > BaseSystem.dmg: 39059732811393335b3ebeac1391aeed905e76de
> 
> While I don't believe these are from Apple, Inc. itself, SHA1 Hashes can be found here: https://github.com/notpeter/apple-installer-checksums

Yes, I'm aware of those, I'm asking:

a) has anyone else downloaded 10.4.3 and obtained hashes that match mine and
b) if so, can those hashes be added to the list of checksums at: https://github.com/notpeter/apple-installer-checksums

**Comment by markmentovai** [comment] 2019-02-25 22:43
> Can anyone confirm these plain (single-file) hashes for 10.4.3 as downloaded from the Apple Store, yesterday? (I assume still current.)
> 
> InstallESD.dmg: 51493681f3e82bb78e22e97f38725ffc67f611cd
> BaseSystem.dmg: 39059732811393335b3ebeac1391aeed905e76de

Those are both correct. I just committed ca85cadaeb11d4aeff436b3c85ebb6c75b63d8c6 with these hashes after verifying them.

(Sorry for the delay. I’m usually able to provide the hashes same-day or day-after-release as a side effect of some process that I have. Someone else took care of that process for 18D109, but not the side effects.)

**Comment by leszek-s** [comment] 2019-02-25 22:54
> InstallESD.dmg: 51493681f3e82bb78e22e97f38725ffc67f611cd
> BaseSystem.dmg: 39059732811393335b3ebeac1391aeed905e76de
> 
> Then doing:
> find /Applications/Install\ macOS\ Mojave.app/ -type f -print0 | sort -z | xargs -0 shasum | shasum
> 
> Using the above command to calculate a single hash for this directory gives me this result:
> c7e7fa5c4d8812bd33c407e1cdae0e7c8dfdb0bc

Yes I can confirm that I get exactly the same hashes for 10.14.3 downloaded from app store (also for the single hash for this whole directory in this path). However note that as I pointed out in my previous post and also as markmentovai pointed out hash from the find command depends on the given path and that is why I wrote that it should be executed with relative path and not the absolute path as you did here. So as I have the same hash for the directory this proves that it kinda works but I agree with markmentovai that it is not perfect. However as this checked over 700 files at once I think it is still useful.

**Closed** 2022-02-11 20:26 UTC
